name: Continuous Integration

on: [push]

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: composer test

      - name: Check coding standards
        run: composer cs-check

      - name: Check static analysis (PHPStan)
        run: composer stan

      - name: Check messdetector
        run: composer md-check
